### ISSUE TITLE
no module named shuffle

### ISSUE THREAD

**Issue by ozett** [chidea/FBpyGIF#21]
hi,
i just installed FBpyGIF with pip3 on a new raspbian stretch (9) on a new raspberry 3.

i got a module-missing error.. (maybe already known)
from last year i remember something, that the pip-repository was not updated?
is it this?

```
root@raspi3a-tft-display:/usr/src/media# FBpyGIF -gd 10 -ad 10 -pv -sf -vb /usr/src/media/
main called with None
main argv revision with ['-gd', '10', '-ad', '10', '-pv', '-sf', '-vb', '/usr/src/media/']
Press Ctrl+C to stop playing
files to play: ['/usr/src/media/mona-lisa-designboom-01.gif', '/usr/src/media/Sergio-Albiac-stardust-portraits-designboom-02.jpg', ... '/usr/src/media/sergio-albiac-learnt-nothing-designboom-07.jpg']
Traceback (most recent call last):
  File "/usr/local/bin/FBpyGIF", line 7, in <module>
    from FBpyGIF.__main__ import main
  File "/usr/local/lib/python3.5/dist-packages/FBpyGIF/__main__.py", line 10, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/FBpyGIF/__main__.py", line 8, in main
    from .main import main as m
  File "/usr/local/lib/python3.5/dist-packages/FBpyGIF/main.py", line 95, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/FBpyGIF/main.py", line 73, in main
    from shuffle import sfcycle
ImportError: No module named 'shuffle'
root@raspi3a-tft-display:/usr/src/media# FBpyGIF -gd 10 -ad 10 -pv -sf -vb /usr/src/media/

```

**Comment by ozett** [comment]
i uninstalled with pip3 and installed the "github"-way,
but same error: "no module shuffle".
but i can see it in the directoy
😕 

```
root@raspi3a-tft-display:/usr/src/FBpyGIF# pip3 uninstall fbpygif
Uninstalling FBpyGIF-1.0.5:
  /usr/local/bin/FBpyGIF
  /usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5.dist-info/DESCRIPTION.rst
  /usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5.dist-info/INSTALLER
  /usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5.dist-info/METADATA
  /usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5.dist-info/RECORD
  /usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5.dist-info/WHEEL
  /usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5.dist-info/entry_points.txt
  /usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5.dist-info/metadata.json
  /usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5.dist-info/top_level.txt
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/__init__.py
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/__main__.py
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/__pycache__/__init__.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/__pycache__/__main__.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/__pycache__/args.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/__pycache__/fb.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/__pycache__/main.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/__pycache__/path.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/__pycache__/shuffle.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/__pycache__/util.cpython-35.pyc
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/args.py
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/fb.py
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/main.py
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/path.py
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/shuffle.py
  /usr/local/lib/python3.5/dist-packages/FBpyGIF/util.py
Proceed (y/n)? y
  Successfully uninstalled FBpyGIF-1.0.5
root@raspi3a-tft-display:/usr/src/FBpyGIF# python3 setup.py install
running install
running bdist_egg
running egg_info
creating FBpyGIF.egg-info
writing FBpyGIF.egg-info/PKG-INFO
writing dependency_links to FBpyGIF.egg-info/dependency_links.txt
writing entry points to FBpyGIF.egg-info/entry_points.txt
writing top-level names to FBpyGIF.egg-info/top_level.txt
writing requirements to FBpyGIF.egg-info/requires.txt
writing manifest file 'FBpyGIF.egg-info/SOURCES.txt'
reading manifest file 'FBpyGIF.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'FBpyGIF.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/FBpyGIF
copying FBpyGIF/util.py -> build/lib/FBpyGIF
copying FBpyGIF/shuffle.py -> build/lib/FBpyGIF
copying FBpyGIF/__main__.py -> build/lib/FBpyGIF
copying FBpyGIF/path.py -> build/lib/FBpyGIF
copying FBpyGIF/__init__.py -> build/lib/FBpyGIF
copying FBpyGIF/args.py -> build/lib/FBpyGIF
copying FBpyGIF/fb.py -> build/lib/FBpyGIF
copying FBpyGIF/main.py -> build/lib/FBpyGIF
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/FBpyGIF
copying build/lib/FBpyGIF/util.py -> build/bdist.linux-armv7l/egg/FBpyGIF
copying build/lib/FBpyGIF/shuffle.py -> build/bdist.linux-armv7l/egg/FBpyGIF
copying build/lib/FBpyGIF/__main__.py -> build/bdist.linux-armv7l/egg/FBpyGIF
copying build/lib/FBpyGIF/path.py -> build/bdist.linux-armv7l/egg/FBpyGIF
copying build/lib/FBpyGIF/__init__.py -> build/bdist.linux-armv7l/egg/FBpyGIF
copying build/lib/FBpyGIF/args.py -> build/bdist.linux-armv7l/egg/FBpyGIF
copying build/lib/FBpyGIF/fb.py -> build/bdist.linux-armv7l/egg/FBpyGIF
copying build/lib/FBpyGIF/main.py -> build/bdist.linux-armv7l/egg/FBpyGIF
byte-compiling build/bdist.linux-armv7l/egg/FBpyGIF/util.py to util.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/FBpyGIF/shuffle.py to shuffle.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/FBpyGIF/__main__.py to __main__.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/FBpyGIF/path.py to path.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/FBpyGIF/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/FBpyGIF/args.py to args.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/FBpyGIF/fb.py to fb.cpython-35.pyc
byte-compiling build/bdist.linux-armv7l/egg/FBpyGIF/main.py to main.cpython-35.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying FBpyGIF.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying FBpyGIF.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying FBpyGIF.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying FBpyGIF.egg-info/entry_points.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying FBpyGIF.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying FBpyGIF.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/FBpyGIF-1.0.5-py3.5.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing FBpyGIF-1.0.5-py3.5.egg
Copying FBpyGIF-1.0.5-py3.5.egg to /usr/local/lib/python3.5/dist-packages
Adding FBpyGIF 1.0.5 to easy-install.pth file
Installing FBpyGIF script to /usr/local/bin

Installed /usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5-py3.5.egg
Processing dependencies for FBpyGIF==1.0.5
Searching for Pillow==5.4.1
Best match: Pillow 5.4.1
Adding Pillow 5.4.1 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Finished processing dependencies for FBpyGIF==1.0.5
root@raspi3a-tft-display:/usr/src/FBpyGIF# FBpyGIF -gd 10 -ad 10 -pv -sf -vb /usr/src/media/
main called with None
main argv revision with ['-gd', '10', '-ad', '10', '-pv', '-sf', '-vb', '/usr/src/media/']
Press Ctrl+C to stop playing
files to play: ['/usr/src/media/mona-lisa-designboom-01.gif', '/usr/src/media/Sergio-Albiac-stardust-portraits-designboom-02.jpg', '/usr/src/media/prepare_to_have_your_mind_altered_01.gif', '/usr/src/media/Sergio-Albiac-stardust-portraits-designboom-06.jpg', '/usr/src/media/sergio-albiac-learnt-nothing-designboom-03.jpg', '/usr/src/media/EGA-palette.png', '/usr/src/media/d70711d8.gif', '/usr/src/media/Sergio-Albiac-stardust-portraits-designboom-03.jpg', '/usr/src/media/source.gif', '/usr/src/media/giphy.gif', '/usr/src/media/sergio-albiac-learnt-nothing-designboom-010.jpg', '/usr/src/media/tumblr_ld5w2xqT8M1qzozj1.gif', '/usr/src/media/sergio-albiac-learnt-nothing-designboom-01.jpg', '/usr/src/media/1560648.gif', '/usr/src/media/AliceCrescendo.gif', '/usr/src/media/NxDv.gif', '/usr/src/media/1_Zo5hOjLkdntV0TKqC_nIWA.gif', '/usr/src/media/Sergio-Albiac-stardust-portraits-designboom-09.jpg', '/usr/src/media/sergio-albiac-learnt-nothing-designboom-08.jpg', '/usr/src/media/665a330d1fe3a227cc565502f8e8cbdc.gif', '/usr/src/media/psychedelic-gifs.gif', '/usr/src/media/0c1ac12d.gif', '/usr/src/media/Sergio-Albiac-stardust-portraits-designboom-10.jpg', '/usr/src/media/sergio-albiac-learnt-nothing-designboom-06.jpg', '/usr/src/media/tenor.gif', '/usr/src/media/Sergio-Albiac-stardust-portraits-designboom-07.jpg', '/usr/src/media/giphy (2).gif', '/usr/src/media/rj38tIf.png', '/usr/src/media/giphy (1).gif', '/usr/src/media/6743333.gif', '/usr/src/media/1531299578_c4ee646b83fe96612bfb34a6a5fa541b.gif', '/usr/src/media/sergio-albiac-learnt-nothing-designboom-09.jpg', '/usr/src/media/sergio-albiac-learnt-nothing-designboom-04.jpg', '/usr/src/media/b3c36f33cd0a41dc7c69ad671b63d18c.gif', '/usr/src/media/photofunky.gif', '/usr/src/media/05.gif', '/usr/src/media/images.jpg', '/usr/src/media/Sergio-Albiac-stardust-portraits-designboom-08.jpg', '/usr/src/media/sergio-albiac-learnt-nothing-designboom-02.jpg', '/usr/src/media/ilusao-de-otica-psicodelica-lsd.jpg', '/usr/src/media/tumblr_ma5nhcoV5P1qf2pkdo1_500.gif', '/usr/src/media/1_HIlG8ZLKuFQtN_D7twpd-g.gif', '/usr/src/media/sergio-albiac-learnt-nothing-designboom-05.jpg', '/usr/src/media/original.gif', '/usr/src/media/sergio-albiac-learnt-nothing-designboom-07.jpg']
Traceback (most recent call last):
  File "/usr/local/bin/FBpyGIF", line 11, in <module>
    load_entry_point('FBpyGIF==1.0.5', 'console_scripts', 'FBpyGIF')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5-py3.5.egg/FBpyGIF/__main__.py", line 10, in <module>
  File "/usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5-py3.5.egg/FBpyGIF/__main__.py", line 8, in main
  File "/usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5-py3.5.egg/FBpyGIF/main.py", line 95, in <module>
  File "/usr/local/lib/python3.5/dist-packages/FBpyGIF-1.0.5-py3.5.egg/FBpyGIF/main.py", line 73, in main
ImportError: No module named 'shuffle'
root@raspi3a-tft-display:/usr/src/FBpyGIF#
```

**Comment by ozett** [comment]
how do in uninstall the "github" thing?
